baseURL = "https://alixdumoulin.netlify.com"
title = "Just another data blog"
copyright = "Copyright © 2020 Alix Dumoulin"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
    
[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Alix Dumoulin"
  description = "Hello there."
  homepageImage = "/images/home-pic.png"
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = false
    email = "example@example.com"
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    stack-overflow = "https://stackoverflow.com"
    instagram = "https://stackoverflow.com"
    github = "https://github.com"
    medium = "https://medium.com"
    reddit = "https://reddit.com"
    gitlab = "https://gitlab.com"
    
  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
